### ISSUE TITLE
Multiple json editors with different schemas doesn't work

### ISSUE THREAD

**Issue by esbakker** [mohsen1/angular-json-schema-form#5]
If you have multiple editors the schemas of the editors get mixed.
Issue can be easily solved: 
````javascript
 var options = angular.extend(SchemaForm.options, {schema: scope.schema});
````
should read:
````javascript
 var options = angular.extend({}, SchemaForm.options, {schema: scope.schema});
````
So that the default config isn't overwritten/extended, but a new options object is created.

**Comment by mohsen1** [comment]
Can you make a pull request for this?

**Comment by esbakker** [comment]
75d93deebcc7e6f56483f882932441a8597a46f7
