### ISSUE TITLE
can you bump the angular version?

### ISSUE THREAD

**Issue by chovy** [mohsen1/angular-json-schema-form#9]
I'm getting a version error when using angular 1.5.3

`1) angular#~1.4.1 which resolved to 1.4.10 and is required by schema-form#0.1.4`

all my other packages resolve to `angular#1.5.3 which resolved to 1.5.3`

**Comment by mohsen1** [comment]
Sure, I'm not sure how Bower handles this but I think we can change the version to `*` in dependencies and what it is in devDependencies so our tests pass. 

If you work on a pull request I'll be happy to merge it.

**Comment by chovy** [comment]
bower.json should just use `angular: ^1.x`

**Comment by mohsen1** [comment]
sounds good! please make a pull request... or I'll do it tonight
